
### 

POST http://localhost:7071/api/graphql
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

{
    users {
        id
        posts {
            id
            comments {
                id
            }
        }
    }
}

###

POST https://explore-functions-stephen.azurewebsites.net/api/graphql
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

{
    users {
        id
        posts {
            id
            comments {
                id
            }
        }
    }
}


###

GET http://localhost:7071/api/getJsonPlaceholderUsers